### ISSUE TITLE
Cannot add pipe in the demo data

### ISSUE THREAD

**Issue by tudorbarascu** [qwat/qwat-data-sample#1]
Hi, 

I was just playing around with the demo data inside a VM that I want to create for demo purposes and I get a `null value in column "fk_node_a" violates not-null constraint`.
I got no errors when restoring (postgresql 9.5, postgis 2.2)

Would it be best to:
- migrate the demo data to the latest data-model and use the latest project
- try and see what's the problem with this one and keep it somewhat exactly like it is + a fitting qwat.qgs
- other options

**Comment by tudorbarascu** [comment]
I also get an error when saving a hydrant: `too many parameters specified for RAISE`
This is an error that was fixed in the data model and in only occurred in Postgresql 9.5.

@ldgeo Do you have an updated dump sitting around or should I migrate to the latest model and make a pull request?

**Comment by ponceta** [comment]
Hi @tudorbarascu, hi @ldgeo, I'm actually trying to export a new sample in a proper way. I face some troubles here : https://github.com/qwat/qwat-data-sample/issues/2
