### ISSUE TITLE
[DEMO SAMPLE] Cannot remove pipes

### ISSUE THREAD

**Issue by ponceta** [qwat/qwat-data-sample#2]
I'm trying to make a proper export for sample data but I face some errors:

I removed entites from hydrants, installations, meter, part, samplingpoint, subscriber, valve elements through the views without issues.

But when trying to remove pipes with :

```
DELETE FROM qwat_od.pipe
WHERE NOT ST_WITHIN(geometry,ST_PolygonFromText('Polygon((540540.655 151779.844, 540540.655 153071.781, 540887.958 153071.781, 540887.958 151779.844, 540540.655 151779.844))',21781));
```

I get following errors :

```
NOTICE:  Delete node 1
CONTEXT:  instruction SQL « SELECT qwat_od.fn_node_set_type(_node_id) »
fonction PL/pgsql qwat_od.fn_node_set_type(integer[]), ligne 12 à PERFORM
instruction SQL « SELECT qwat_od.fn_node_set_type( node_ids ) »
fonction PL/pgsql qwat_od.ft_pipe_node_type(), ligne 19 à PERFORM
NOTICE:  Delete node 2
CONTEXT:  instruction SQL « SELECT qwat_od.fn_node_set_type(_node_id) »
fonction PL/pgsql qwat_od.fn_node_set_type(integer[]), ligne 12 à PERFORM
instruction SQL « SELECT qwat_od.fn_node_set_type( node_ids ) »
fonction PL/pgsql qwat_od.ft_pipe_node_type(), ligne 19 à PERFORM


ERREUR:  l'enregistrement « new » n'est pas encore affectée
DETAIL:  La structure de ligne d'un enregistrement pas encore affecté est indéterminée.
CONTEXT:  instruction SQL « UPDATE qwat_od.vw_element_valve valve SET fk_pipe = qwat_od.fn_pipe_get_id(geometry) WHERE fk_pipe = OLD.id OR ST_Distance(geometry, NEW.geometry) < 1e-4 »
fonction PL/pgsql qwat_od.ft_valve_pipe_update(), ligne 3 à instruction SQL
********** Error **********

ERREUR: l'enregistrement « new » n'est pas encore affectée
SQL state: 55000
Detail: La structure de ligne d'un enregistrement pas encore affecté est indéterminée.
Context: instruction SQL « UPDATE qwat_od.vw_element_valve valve SET fk_pipe = qwat_od.fn_pipe_get_id(geometry) WHERE fk_pipe = OLD.id OR ST_Distance(geometry, NEW.geometry) < 1e-4 »
fonction PL/pgsql qwat_od.ft_valve_pipe_update(), ligne 3 à instruction SQL
```

**Comment by tudorbarascu** [comment]
Hi, You're trying to remove the pipes from the sample data in this repo, right?
I'm going to try and find time this weekend to make a migration of the sample data to the new model and then see what's happening.

**Comment by ldgeo** [comment]
Hi, yes trying to make a migration is a good idea. 
@sylvainbeo do you have an updated version of this data sample or have you ever seen this kind of error ?

**Comment by ponceta** [comment]
Actually I try to redo this sample extract from our data to provide a clean data sample (to avoid troubles).

**Comment by ponceta** [comment]
```
Context: instruction SQL « UPDATE qwat_od.vw_element_valve valve SET fk_pipe = qwat_od.fn_pipe_get_id(geometry) WHERE fk_pipe = OLD.id OR ST_Distance(geometry, NEW.geometry) < 1e-4 »
fonction PL/pgsql qwat_od.ft_valve_pipe_update(), ligne 3 à instruction SQL
```

Means that I still have a valve on my pipe right?
Although I deleted Valves outside the box using:

```
-- //VALVE //
-- REMOVE ELEMENT VALVE NOT IN SELECTION
DELETE FROM qwat_od.vw_element_valve
WHERE NOT ST_WITHIN(geometry,ST_PolygonFromText('Polygon((540540.655 151779.844, 540540.655 153071.781, 540887.958 153071.781, 540887.958 151779.844, 540540.655 151779.844))',21781));
DELETE FROM qwat_od.vw_element_valve
WHERE NOT ST_WITHIN(geometry_alt1,ST_PolygonFromText('Polygon((540540.655 151779.844, 540540.655 153071.781, 540887.958 153071.781, 540887.958 151779.844, 540540.655 151779.844))',21781));
DELETE FROM qwat_od.vw_element_valve
WHERE NOT ST_WITHIN(geometry_alt2,ST_PolygonFromText('Polygon((540540.655 151779.844, 540540.655 153071.781, 540887.958 153071.781, 540887.958 151779.844, 540540.655 151779.844))',21781));
```

**Comment by tudorbarascu** [comment]
as you used `not st_within` the polygon, it means that you're deleting all the pipes that are not **fully contained** in the polygon. So, you may try to delete a pipe that's simply crossing the polygon border and that may have valves inside the polygon and you haven't deleted that valve according to your query.
Does it make sense to you?

**Comment by tudorbarascu** [comment]
So, you may update your pipe deletion query with `ST_Intersects` and check if it works (it should work).

**Comment by ponceta** [comment]
It makes sense to me, and it changes the number of pipes concerned correctly. But I still get a similar error using intersect.

**Comment by ponceta** [comment]
I tried it on QGIS to have more visual:
SELECTING intersects with a crop mask (points are remaining valves, hydrants, ... )
![image](https://cloud.githubusercontent.com/assets/8614223/15921849/cdb8fc38-2e24-11e6-8acc-4a46ee266f64.png)

Inverse the selection
![image](https://cloud.githubusercontent.com/assets/8614223/15921883/0193fc42-2e25-11e6-8905-1c3477074c84.png)

Try to remove selected pipes
![image](https://cloud.githubusercontent.com/assets/8614223/15921915/3a99e59c-2e25-11e6-9032-b7bf483a5782.png)

Impossible de valider les changements pour la couche pipe

```
Erreurs : ERREUR : 8975 attributs non effacés.

Erreur du fournisseur de données :
      Erreur PostGIS lors de la suppression d'entité : ERREUR:  l'enregistrement « new » n'est pas encore affectée
    DETAIL:  La structure de ligne d'un enregistrement pas encore affecté est indéterminée.
    CONTEXT:  instruction SQL « UPDATE qwat_od.vw_element_valve valve SET fk_pipe = qwat_od.fn_pipe_get_id(geometry) WHERE fk_pipe = OLD.id OR ST_Distance(geometry, NEW.geometry) < 1e-4 »
    fonction PL/pgsql qwat_od.ft_valve_pipe_update(), ligne 3 à instruction SQL
```

(same as pg, which is at least logical :)

**Comment by ldgeo** [comment]
Hi, 
don't know if it could help but after looking at last commits in the data-model repo, @3nids may have fixed it in https://github.com/qwat/qwat-data-model/commit/6dca3bb76612fad67639ab24e1dd3e8af9ef518c ?

**Comment by ponceta** [comment]
That's probably it! My data model is still at the last migration status.
