### ISSUE TITLE
Can't load qwat data sample

### ISSUE THREAD

**Issue by avicomartin** [qwat/qwat-data-sample#5]
Hi all,
I want test qwat data sample but I can't load data into the database.

I'm using a VM (a VM with qgep instaled downloaded from qgep site, that is a debian jessie distribution) and installed successfully a qwet database following https://github.com/qwat/QWAT instructions.

In order to use sample data I have created a new database (qwatsample), I have added extensions and have tried to load data with pgAdmin III. Using Restore from popup menu fails (not show object to restore) and when I try to load in the sql editor as a sql script, it fails loading spatial_ref_sys table (ERROR:  syntax error at or near "5013", that is the first line in spatial_ref_sys table).

Using psql command show a lot of messages about "invalid command \N" with wrong result.

Has someone loaded data sample successfully? If yes, How to?

**Comment by tudorbarascu** [comment]
@avicomartin Hi, I will try and do a vm with qwat data this weekend.
If you're in a hurry you should:
- create a database model from here (optional but it may help you..at least with the roles)
- restore data from my pull request here: https://github.com/qwat/qwat-data-sample/pull/4

**Comment by avicomartin** [comment]
Hi Tudor, thanks for your reply.

If you really do a VM this weekend I think I can wait a couple of days :-). 
Will you include both qgep and qwat in this VM?

**Comment by tudorbarascu** [comment]
for now just **qwat**

**Comment by tudorbarascu** [comment]
@avicomartin The VM will be available in few hours. Meanwhile you can checkout https://github.com/tudorbarascu/qwat-data-sample/blob/master/README.md if you want to recreate the data sample.

**Comment by avicomartin** [comment]
Hi Tudor, thanks for sharing.

I just have loaded this data into qgep virtual machine successfully 
following the steps in readme.md

**Comment by tudorbarascu** [comment]
The vm is ready and in the docs. You can close this issue if everything is ok.

**Comment by avicomartin** [comment]
Hi Tudor, thanks for your work.
I'm just playing with this data and in qwat there are some layers displaced from anothers. Layers folios and couvercles are displaced respect all other data (maybe is consequence to make data anonymous respect real situation)

**Comment by tudorbarascu** [comment]
Indeed I forgot to delete the features in the folios and couvercles layers (on account of the reasons aforementioned by you, also mentioned at https://github.com/qwat/qwat-data-sample/issues/3)
Will do so.
